const products = [
  {
    id: 1,
    name: "SHIRT MEN 1",
    categoryName: "SHIRT MEN",
    description: "Ao so mi tay dai mau xam",
    price: 700000,
    priceSale: 500000,
    imageURL: "images/shirt1.jpg",
    category: "Nam",
    tags: ["noi bat", "sale 30%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 2,
    name: "SHIRT MEN 2",
    categoryName: "SHIRT MEN",
    description: "Ao so mi tay dai mau xanh ",
    price: 700000,
    priceSale: 500000,
    imageURL: "images/shirt2.jpg",
    category: "Nam",
    tags: ["noi bat", "sale 30%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 3,
    categoryName: "SHIRT MEN",
    name: "SHIRT MEN 3",
    description: "Ao thun soc xanh trang ",
    price: 700000,
    imageURL: "images/shirt3.jpg",
    category: "Nam",
    tags: ["noi bat"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 4,
    name: "SHIRT MEN 4",
    categoryName: "SHIRT MEN",
    description: "Ao thun trang va so mi xanh ",
    price: 700000,
    imageURL: "images/shirt4.jpg",
    category: "Nam",
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 5,
    name: "SHIRT WOMAN 1",
    categoryName: "SHIRT WOMAN",
    description: "Do ngu mau hong ",
    price: 300000,
    imageURL: "images/shirt5.jpg",
    category: "Nu",
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 6,
    name: "SHIRT WOMAN 2",
    categoryName: "SHIRT WOMAN",
    description: "Ao len nu mau hong ",
    price: 700000,
    imageURL: "images/shirt6.jpg",
    category: "Nu",
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 7,
    name: "SHIRT WOMAN 3",
    categoryName: "SHIRT WOMAN",
    description: "Ao len nu mau be ",
    price: 700000,
    imageURL: "images/shirt7.jpg",
    category: "Nu",
    tags: ["noi bat"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 8,
    name: "SHIRT WOMAN 4  ",
    categoryName: "SHIRT WOMAN",
    description: "Do ngu mau den ",
    price: 300000,
    imageURL: "images/shirt8.jpg",
    category: "Nu",
    tags: ["noi bat"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 9,
    name: "WEATER 1",
    categoryName: "SWEATER",
    description: "Ao Weater 3 mau ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt9.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat", "sale 40%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 10,
    name: "WEATER 2",
    categoryName: "SWEATER",
    description: "Ao Weater mau den ",
    price: 700000,
    imageURL: "images/shirt10.jpg",
    category: ["Nam", 'Nu'],
    priceSale: 400000,
    tags: ["sale 40%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 11,
    name: "WEATER 3",
    categoryName: "SWEATER",
    description: "Ao Weater mau do ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt11.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 12,
    name: "WEATER 4",
    categoryName: "SWEATER",
    description: "Ao Weater mau be ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt12.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 13,
    name: "T SHIRT 1",
    categoryName: "T SHIRT",
    description: "ao thun den",
    price: 400000,
    priceSale: 280000,
    imageURL: "images/shirt13.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat", "sale 30%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 14,
    name: "T SHIRT 2",
    categoryName: "T SHIRT",
    description: "ao thun mau hong ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt14.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat", "sale 30%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 15,
    name: "T SHIRT 3",
    categoryName: "T SHIRT",
    description: "ao thun den tay ngan ",
    price: 400000,
    priceSale: 280000,
    imageURL: "images/shirt15.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat", "sale 30%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 16,
    name: "T SHIRT 4",
    categoryName: "T SHIRT",
    description: "ao thun mau nau",
    price: 400000,
    imageURL: "images/shirt16.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 17,
    name: "T SHIRT 5",
    categoryName: "T SHIRT",
    description: "ao thun mau trang",
    price: 500000,
    imageURL: "images/shirt17.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 18,
    name: "T SHIRT 6",
    categoryName: "T SHIRT",
    description: "ao thun mau be ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt18.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 19,
    name: "T SHIRT 7",
    categoryName: "T SHIRT",
    description: "ao thun mau hong ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt19.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 20,
    name: "T SHIRT 8",
    categoryName: "T SHIRT",
    description: "Ao Weater mau be ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt20.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%", "sale"],
    sizes: ['S', 'M', 'L', 'XL'],
  },
];
//
const user = {
  fullName: "Nguyễn Văn A",
  email: "nguyenvana@example.com",
  orders: [
    {
      id: "DH001",
      date: "2025-07-10",
      total: "500.000₫",
      status: "Đã giao"
    },
    {
      id: "DH002",
      date: "2025-07-15",
      total: "1.200.000₫",
      status: "Đang xử lý"
    },
    {
      id: "DH003",
      date: "2025-07-20",
      total: "750.000₫",
      status: "Đã hủy"
    }
  ]
};

const imagesList = [
  "images/silde-show1.jpg",
  "images/silde-show2.jpg",
  "images/silde-show3.jpg",
]
export {
  products, imagesList, user
}